### ISSUE TITLE
Auto-generate the release notes upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/smtpapi-php#101]
#### Issue Summary

For every release, we hand craft the release notes on GitHub, now we would like to automate this process. Please see the existing [release notes](https://github.com/sendgrid/smtpapi-php/releases) for an example. The contents of the release notes are generated from the CHANGELOG.md file. [Here](https://developer.github.com/v3/repos/releases/#create-a-release) is the documentation for updating the release notes via the GitHub API. 

#### Acceptance Criteria
 

* A script, which when run, creates a release note update based on the last deployed release

**Comment by pxgamer** [comment]
As its nearing the end of Hacktoberfest, mind if I take a look at this one?

**Comment by pxgamer** [comment]
Getting the contents out of the CHANGELOG file is easy, I've got that working locally.

I was just wondering, should this be part of the Travis release process? Or a standalone script?
