### ISSUE TITLE
README.md, Swiftmailer example, Call to undefined method Swift_Message::setTos()

### ISSUE THREAD

**Issue by waitman** [sendgrid/smtpapi-php#12]
PHP Fatal error:  Uncaught Error: Call to undefined method Swift_Message::setTos()

$message->setTos(array('bar@blurdybloop.com'));

should probably be

$message->setTo(array('bar@blurdybloop.com'));

**Comment by thinkingserious** [comment]
Good catch @waitman, this was fixed: https://github.com/sendgrid/smtpapi-php/blob/master/examples/swift_mailer.php#L21

Thanks!
