### ISSUE TITLE
Question: is the line-wrapping missing?

### ISSUE THREAD

**Issue by janrop** [sendgrid/smtpapi-php#15]
In the [documentation](https://sendgrid.com/docs/API_Reference/SMTP_API/using_the_smtp_api.html#-Requirements-and-Limitations) it says that lines should be wrapped:

> Headers must be wrapped to keep the line length under 72. By [RFC 821](http://tools.ietf.org/html/rfc821) no line can be longer than 1,000, so if you are going to generate this string yourself it is a good idea to make sure that you wrap it.

Is this missing here, or should it be done elsewhere?

**Comment by thinkingserious** [comment]
Hi @janrop,

This library does not handle that; however, this is no longer an issue with the latest version of the https://github.com/sendgrid/sendgrid-php library. Thanks!

**Comment by nikoskip** [comment]
For those who need to manage this, there is a function in PHP called [chunk_split](http://php.net/manual/es/function.chunk-split.php).

<?php

$json = chunk_split($header->jsonString(), 72);
