### ISSUE TITLE
Why is Swift Mailer a dependency?

### ISSUE THREAD

**Issue by nikoskip** [sendgrid/smtpapi-php#27]
Hi!

I'm trying to update to version `0.6` but I can't because in my project I'm currently using Swift Mailer version 6 and this package needs Swift Mailer `^5.4`.

Maybe needs to be a `dev` dependency instead a production one, considering that it's only being used on the examples scripts:

```
"require-dev": {
        "phpunit/phpunit": "3.7.*",
        "swiftmailer/swiftmailer": "^5.4"
}
```

Or maybe a `suggest`:

```
"suggest": {
        "swiftmailer/swiftmailer": "^5.4 - Needed to run the example scripts"
}
```

BTW, you might need to update the `README.md` to reflect the new version on "Install with Composer" section.

Cheers!

**Comment by thinkingserious** [comment]
Hello @nikoskip,

I like the `suggest` option and update the README.md now.

I've added this to our backlog to update, but it will not likely be high on the list. If you choose to make a PR, it jumps up the queue.

Thanks!

With Best Regards,

Elmer

**Comment by nikoskip** [comment]
@thinkingserious your wishes comes true!

Cheers!

**Comment by nikoskip** [comment]
@thinkingserious Packagist is not reading the updates on the `composer.json` file. Maybe you need to set a new version? `0.6.1`?

**Comment by thinkingserious** [comment]
Looks like it was updated, but the not the badge: https://packagist.org/packages/sendgrid/smtpapi#0.6.0

I'm not quite sure why

**Comment by nikoskip** [comment]
The badge it's now updated but not the content of the `composer.json` file. Maybe if you manually triggers the update on Packagist could fix the problem. I'm not really an expert using Packagist 😄

**Comment by thinkingserious** [comment]
Ah, I'm guessing I do need to make a point release then. I'll give that a try. Thanks!
