### ISSUE TITLE
Word-wrap the smtpapi-header before 998 chars

### ISSUE THREAD

**Issue by Creamailer** [sendgrid/smtpapi-php#8]
The string from jsonString function needs to be word-wrapped to work in all situations (also with SMTP, not only with HTTP). 

The standards document for the format of e-mail messages, RFC 2822 (the successor to RFC 822, the classic document that established the standards that have been followed ever since), says this about the length of lines in an e-mail message: Line length SHOULD be less than 78 characters and MUST be 998 or less, including CRLF. 

Example when using Postfix relay server, longer lines (than 998) are broken by inserting "CR + LF + SPACE", to minimize the damage to MIME formatted mail. Many times this breaks the smtpapi-header json and email SendGrid returns "Invalid SMTPAPI Header" -email notification. Error messages are hard to track down since the error can come up pretty much anywhere in the smtpapi-header. 

Might be good idea to implement the word-wrapping near 1000 chars since the smtpapi-header can be really big sometimes if you use lots of substitution tags like I do. Also the word-wrapping needs to happen after tags like "]," to keep the json valid.

**Comment by thinkingserious** [comment]
@Creamailer thanks for the suggestion! I'm adding it to the roadmap.

**Comment by thinkingserious** [comment]
Hello @Creamailer,

This is no longer an issue with the latest version of this library. ThankS!
