### ISSUE TITLE
Cannot build or test locally

### ISSUE THREAD

**Issue by jmauerhan** [sendgrid/smtpapi-php#91]
#### Issue Summary

I wanted to work on a fix for an issue reported here, but I am unable to run the existing tests locally or in CI, due to a test for files which do not exist in the repo. There is a test which checks for two Dockerfiles, which are not part of the repo, and the instructions to build and test locally don't include any info on creating these files. 

#### Steps to Reproduce

1. Clone the repo
2. composer install
3. run the tests as instructed in the docs

#### Technical details:

* smtpapi-php Version: master (latest commit: [729d8e8690e255559bc4d81d41546aff8d5fd987])
* PHP Version: 5.6 and 7.0

**Comment by thinkingserious** [comment]
Hello @jmauerhan,

You can comment out those failing tests [here](https://github.com/sendgrid/smtpapi-php/blob/master/test/RepoFilesExists.php). Thanks!

With Best Regards,

Elmer

**Comment by jmauerhan** [comment]
Yeah, I actually started on a PR to fix up the tests, cause those are actually the only tests that run anyway 🤣 Having some issues with it.

**Comment by jmauerhan** [comment]
Finally got everything working in CI too, the casing of the directory was the issue.
