### ISSUE TITLE
Auto-generate the CHANGELOG.md file upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/smtpapi-php#96]
#### Issue Summary

For every release, we currently hand craft a CHANGELOG.md update, now we would like to automate this process. Please see the existing CHANGELOG.md for formatting structure.

#### Acceptance Criteria

* A script, which when run, creates a CHANGELOG.md update based on any merged PRs since the last release.

**Comment by jmauerhan** [comment]
I'd like to work on this, I actually have a script that does this already for generating the release notes in the tag, based on merged PRs - but it doesn't have "Fixed" vs "Added". 

I'm thinking maybe the script could get the list of merged PRs, then prompt the user to choose whether this is "Fixed" or "Added", and also allow them to add any notes to it for the "Thanks" lines you have as well. Then it could generate the Change Log addition from that. 

Does that sound good to y'all?

**Comment by childish-sambino** [comment]
Closing as we're moving to internal tooling for automated changelog generation.
